name: palbang_server
description: 팔방 Dart 서버
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.18.0 <3.0.0'

# Add regular dependencies here.
dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  shelf_cors_headers: ^0.1.5
  mongo_dart: ^0.10.0
  dart_jsonwebtoken: ^2.8.2
  path: ^1.8.3
  mime: ^1.0.4
  shelf_multipart: ^1.0.0
  crypto: ^3.0.2
  # 실제 DB 연동 시 mongo_dart, mysql1 등 추가 가능

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
